language: node_js
node_js:
- '0.10'
notifications:
  email:
    on_success: change
    on_failure: change
before_script:
- gem install sass --version "=3.2.12"
- gem install compass --version "=0.12.2"
- npm install -g bower grunt-cli
- bower install
